version: '2' #cdocker-compose版本
services: #所有服务集合
  mysql: #官方mysql数据库服务
    image: mysql:5.7 #镜像源
    restart: always #异常退出后重启
    env_file: .env #导入配置变量
    environment: #容器中环境变量
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}" #数据库root用户密码
      MYSQL_DATABASE: "${DB_DATABASE}" #新创建数据库名称
      MYSQL_USER: "${DB_USERNAME}" #数据库用户名
      MYSQL_PASSWORD: "${DB_PASSWORD}" #数据库密码
    volumes: #数据卷,挂载目录
      - "../data/mysql:/var/lib/mysql" #mysql数据库数据文件存放目录;宿主机目录:容器目录
    ports: #与宿主进的端口映射
      - "${DB_PORT}:3306" #宿主机端口:容器端口
  redis: #官方redis服务
    build: ./docker/redis
    restart: always #异常退出后重启
    env_file: .env #导入配置变量
    environment: #容器中环境变量
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - ../data/redis:/data #redis数据文件存放目录
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: > #设置redis启动密码
      --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
  tool: #工具容器(包含:composer,npm,cnpm,git,php,node...)
    build: ./docker/tool
    depends_on:
      - mysql
      - redis
    volumes: #挂载php配置项
      - ".:/home/www"
      - "../cai:/var/www/cai-sys" #代码目录
      - "../cai-user:/var/www/cai-user"
      - "../adoc:/var/www/adoc"
      - "../test-api:/var/www/test-api"
      - "./docker/tool/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./docker/tool/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./docker/tool/php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/tool/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    links:
      - mysql:db
      - redis:redis
    entrypoint: #挂起容器不退出
      tail -f /etc/passwd
  php: #官方php服务
    build: ./docker/php
    depends_on:
      - tool
    restart: always
    volumes:
      - "../cai:/var/www/cai-sys" #代码目录
      - "../cai-user:/var/www/cai-user"
      - "../adoc:/var/www/adoc"
      - "../test-api:/var/www/test-api"
      - "./docker/php/ini/php.ini-development:/usr/local/etc/php/php.ini" #php配置文件
      - "./docker/php/ini/www.conf:/usr/local/etc/php-fpm.d/www.conf" # php-fpm配置文件
    links:
      - mysql:db
      - redis:redis
  nginx: #官方nginx服务器服务
    image: nginx:1.15
    depends_on:
      - php
    restart: always
    volumes:
      - "../cai:/var/www/cai-sys" #代码目录
      - "../cai-user:/var/www/cai-user"
      - "../adoc:/var/www/adoc"
      - "../test-api:/var/www/test-api"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/vhost:/etc/nginx/conf.d/vhost"
    ports:
      - "80:80"
    links:
      - php:php-fpm